POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "SF ENthusiasts",
    "author": "M. Night Shyamalan",
    "url": "r/streetfighter",
    "likes": 13
}

### POST INVALID ITEM
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
}

### POST INVALID ITEM, MISSING PARAMS
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "SF ENthusiasts",
    "author": "M. Night Shyamalan",
    "url": "r/streetfighter"
}