POST http://localhost:3001/api/blogs
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "title": "Garlic and Pepper",
    "url": "google.com",
    "author": "Andre Spiceman",
    "likes": 305
}

### INVALID TOKEN
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "title": "second test blog",
    "url": "test.com",
    "likes": 110
}

### NO BEARER TOKEN
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "second test blog",
    "url": "test.com",
    "likes": 110
}

### POST INVALID ITEM
POST http://localhost:3001/api/blogs
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
}

### POST INVALID ITEM, MISSING PARAMS
POST http://localhost:3001/api/blogs
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "author": "M. Night Shyamalan",
    "url": "r/streetfighter"
}